<a href="https://colab.research.google.com/github/sou7500/Sample_prob/blob/main/counting_strings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
x= np.array([1,2,3,4,5,6])
y= np.resize(x,(3,4))
y



array([[1, 2, 3, 4],
       [5, 6, 1, 2],
       [3, 4, 5, 6]])

In [ ]:
x= np.array([1,2,3,4,5,6])
x.resize(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0]])

In [ ]:
x=[[1,2,3],[4,5,6]]
arr= np.array(x)
y=arr.reshape(3,2)
z= y.flatten()
z

array([1, 2, 3, 4, 5, 6])

In [ ]:
a= '123skhVGHehW$sj&*'
lower= 0
upper= 0
symbol=0
number=0
for i in a:
  if (i.islower()):
    lower+=1
for i in a:
  if(i.isupper()):
    upper+=1
for i in a:
  if(i.isnumeric()):
    number+=1
symbol= len(a)-(lower + upper + number)
print(f'The number of upper letter is {upper}')
print(f'The number of lower letter is {lower}')
print(f'The number of symbols is {symbol}')
print(f'The number in strings is {number}')


The number of upper letter is 4
The number of lower letter is 7
The number of symbols is 3
The number in strings is 3


In [ ]:
sample = input('Please enter example string for testing ')
unique_value= list(set(sample))
freq = 0
print(unique_value)

for i in unique_value:
  freq= sample.count(i)
  print(f'{i} occured {freq} times in this string')
  


# count= 0
# for i in a:
#   for j in sample:
#     if (i == j):
#       count+=1
#       print(f'{i} occured {count} times in this string')

Please enter example string for testing turttretttwiiihqbbbhjjinncfyjwk
['j', 'u', 't', 'r', 'c', 'e', 'b', 'y', 'i', 'h', 'n', 'f', 'w', 'q', 'k']
j occured 3 times in this string
u occured 1 times in this string
t occured 6 times in this string
r occured 2 times in this string
c occured 1 times in this string
e occured 1 times in this string
b occured 3 times in this string
y occured 1 times in this string
i occured 4 times in this string
h occured 2 times in this string
n occured 2 times in this string
f occured 1 times in this string
w occured 2 times in this string
q occured 1 times in this string
k occured 1 times in this string
